"""
NEW LAYOUT 7/30
"""

"""
Window Size
"""
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

"""
Title Size
"""
TITLE_X = 200
TITLE_Y = 25
TITLE_WIDTH = 400
TITLE_HEIGHT = 50

"""
Game Grid Size
"""
CELL_SIZE = 40
GRID_ROWS = 10
GRID_COLS = 10
GRID_WIDTH = GRID_COLS * CELL_SIZE
GRID_HEIGHT = GRID_ROWS * CELL_SIZE

GRID_ML = 40  # margin left
GRID_MR = 360  # margin right
GRID_MT = 100  # margin top
GRID_MB = 100  # margin bottom

"""
Header Size
"""
HEADER_WIDTH = 340
HEADER_HEIGHT = 40
METRICS_X = 40 + GRID_WIDTH + 10
METRICS_Y = 100

CONTROLS_X = 40 + GRID_WIDTH + 10
CONTROLS_Y = 100 + HEADER_HEIGHT + 20 + HEADER_HEIGHT + 10 + 52

HEADER_ML = 10
HEADER_MR = 10
HEADER_MT = 100
HEADER_MB = 20

"""
Large Button Size
"""
L_BUTTON_HEIGHT = 340
L_BUTTON_WIDTH = 40

"""
Small Button Size
"""
S_BUTTON_WIDTH = 160
S_BUTTON_HEIGHT = 40

"""
Button Margin
"""
S_BUTTON_M = 10
L_BUTTON_M = 20
H_BUTTON_M = 52

"""
Pause Button
"""
PAUSE_X = 40
PAUSE_Y = 600 - 80

"""
Reset Button
"""
RESET_X = 40 + S_BUTTON_WIDTH + 80
RESET_Y = 600 - 80

"""
Score Display
"""
SCORE_WIDTH = 160
SCORE_HEIGHT = 40
SCORE_X = 40 + GRID_WIDTH + 10
SCORE_Y = 100

"""
Steps Display
"""
STEPS_WIDTH = 160
STEPS_HEIGHT = 40
STEPS_X = SCORE_X + SCORE_WIDTH + 20
STEPS_Y = SCORE_Y

"""
Coins Display
"""
COINS_WIDTH = 160
COINS_HEIGHT = 40
COINS_X = 40 + GRID_WIDTH + 10
COINS_Y = SCORE_Y + SCORE_HEIGHT + 10

"""
Trash Display
"""
TRASH_WIDTH = 160
TRASH_HEIGHT = 40
TRASH_X = COINS_X + COINS_WIDTH + 20
TRASH_Y = COINS_Y


"""
Step Buttons
"""
STEP_BTN_WIDTH = 75
STEP_BTN_HEIGHT = 40

"""
Step Limit Group
"""
STEP_GRP_WIDTH = 160
STEP_GRP_HEIGHT = 40
STEP_GRP_X = COINS_X
STEP_GRP_Y = COINS_Y + COINS_HEIGHT + 16

"""
Coin Group
"""
COIN_GRP_WIDTH = 160
COIN_GRP_HEIGHT = 40
COIN_GRP_X = STEP_GRP_X
COIN_GRP_Y = STEP_GRP_Y + STEP_GRP_HEIGHT + 10

"""
Trash Group
"""
TRASH_GRP_WIDTH = 160
TRASH_GRP_HEIGHT = 40
TRASH_GRP_X = COIN_GRP_X
TRASH_GRP_Y = COIN_GRP_Y + COIN_GRP_HEIGHT + 10

"""
Game Object Group
"""
OBJ_GRP_WIDTH = 40
OBJ_GRP_HEIGHT = 40
OBJ_GRP_X = TRASH_GRP_X
OBJ_GRP_Y = TRASH_GRP_Y + TRASH_GRP_HEIGHT + 16
OBJ_GRP_PAD = 110

"""
Algorithms Group
"""
ALGO_GRP_WIDTH = 160
ALGO_GRP_HEIGHT = 20
ALGO_GRP_X = OBJ_GRP_X
ALGO_GRP_Y = OBJ_GRP_Y + OBJ_GRP_HEIGHT + 16
ALGO_GRP_PAD = 20

"""
Dialogue Window
"""
DW_WIDTH = 340
DW_HEIGHT = 60
DW_X = ALGO_GRP_X
DW_Y = ALGO_GRP_Y + 80 + 16
DW_PAD = 20
